reviews:
  profile: assertive
  path_filters:
    - "!bin/**"
    - "!stdlib/**"
    - "!include/stb/**"
    - "!include/stdlib/**"
    - "!include/etl/**"
    - "!core/tlsf/**"
    - "!include/core/tlsf/**"
    - "!core/filesystem/FatFs/**/*.c"
    - "!include/core/filesystem/FatFs/**"
